name: Build and deploy Python project to Azure Function App (manual zip) - jira-azure-validator
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into package folder
        run: |
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Prepare artifact structure
        run: |
          mkdir deploy
          cp requirements.txt host.json .funcignore -t deploy/
          cp -r HttpTrigger deploy/
          cp -r .python_packages deploy/
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AFD13D0E1AC640FE9E88EC9ED7F81B14 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0411E2EDB6BC40ECB10E3B88882800DA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4077DFA01ACB49F89F1C5CA6A4B441A7 }}

      - name: Deploy to Azure Functions (manual zip)
        uses: Azure/functions-action@v1
        with:
          app-name: 'jira-azure-validator'
          package: release.zip
          scm-do-build-during-deployment: false
          enable-oryx-build: false
